image:
  repository: cptmeh/webapp

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 40

deployment:
  enabled: true
  ports:
  - http:
      container: 8080
  resources:
    requests:
      cpu: "0.2"
      memory: "32Mi"
    limits:
      cpu: "0.5"
      memory: "64Mi"
  probes:
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
  securityContext:
    id: 101

service:
  enabled: true

serviceAccount:
  enabled: true
