name: CD

on:
  push:
    tags:
      - staging-*
      - uat-*
      - production-*

jobs:
  trigger-deployment:
    uses: lneves75/gh-workflows/.github/workflows/deployment.yaml@0c495aa7ca28ab461578cb0ffa32174eb004c433
    with:
      service: 'webapp'
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITOPS_TOKEN }}
