name: CD

on:
  push:
    tags:
    - staging-**
    - uat-**
    - production-**

env:
  APP: webapp

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Argo Apps
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: lneves75/argocd-apps
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Get target environment
        id: environment
        run: |
          echo "name=$(echo ${{ github.ref_name }} | awk -F'-' '{print $1}')" >> $GITHUB_OUTPUT

      - name: Set tag for environment
        if: github.event_name == 'push'
        working-directory: apps
        env:
          environment: ${{ steps.environment.outputs.name }}
          envIndexExp: ".spec.generators[0].matrix.generators[0].list.elements[] | select(.environment == env(environment)) | key"
          tagExp: ".spec.generators[0].matrix.generators[0].list.elements[env(envIndex)].tag"
        run: |
          export envIndex=$(yq 'eval(env(envIndexExp))' ${{ env.APP }}.yaml)
          echo "Current tag: $(yq 'eval(env(tagExp))' ${{ env.APP }}.yaml)"
          yq 'eval(env(tagExp)) = "${{ github.sha }}"' -i ${{ env.APP }}.yaml
          git diff ${{ env.APP }}.yaml

      - name: Commit changes to git
        if: github.event_name == 'push'
        env:
          environment: "staging"
        run: |
          if [ $(git status --short | wc -l) -gt 0 ]; then
            commit_message="${{ env.APP }}[${{ github.sha }}] deployed to ${{ env.environment }}"
            git config user.name lneves75
            git config user.email luis.neves@on.com
            git add apps/${{ env.APP }}.yaml
            git commit -m "${commit_message}" -m"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
          fi
  
      - name: Rebase and push new commits.
        if: github.event_name == 'push'
        uses: nick-fields/retry@v3
        with:
          retry_on: error
          max_attempts: 3
          timeout_seconds: 15
          command: |
            git remote add origin https://github.com/lneves75/argocd-apps.git
            git pull --rebase origin master && \
            git push
