name: CD

on:
  push:
    tags:
      - staging-*
      - uat-*
      - production-*

jobs:
  trigger-deployment:
    uses: lneves75/gh-workflows/.github/workflows/deployment.yaml@fe7721a189eb09a99afaea527b75918352e8f42e
    with:
      service: 'webapp'
      tag: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.GITOPS_TOKEN }}
