name: CI

on:
  push:
    branches:
      - master
  pull_request: 

env:
  APP: webapp

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get image tag
        id: image
        run: |
          if [ "${{ github.event_name }}" != 'push' ]; then
            echo "tag=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.image.outputs.tag }}

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args:
           COMMIT_HASH=${{ steps.image.outputs.tag }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP }}:${{ steps.image.outputs.tag }}

      - name: Checkout Argo Apps
        # if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: lneves75/argocd-apps
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Set tag for environment
        # if: github.event_name == 'push'
        working-directory: apps
        env:
          env: "uat"
          envIndexExp: ".spec.generators[0].matrix.generators[0].list.elements[] | select(.environment == env(env)) | key"
          tagExp: ".spec.generators[0].matrix.generators[0].list.elements[env(envIndex)].tag"
        run: |
          export envIndex=$(yq 'eval(env(envIndexExp))' ${{ env.APP }}.yaml)
          echo "Current tag: $(yq 'eval(env(tagExp))' ${{ env.APP }}.yaml)"
          yq 'eval(env(tagExp)) = "${{ steps.image.outputs.tag }}"' -i ${{ env.APP }}.yaml
          git diff ${{ env.APP }}.yaml
