name: CI

on:
  push:
    branches:
      - master
  pull_request: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get image tag
        id: image
        run: |
          if [ "${{ github.event_name }}" != 'push' ]; then
            echo "tag=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.image.outputs.tag }}

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args:
           COMMIT_HASH=${{ steps.image.outputs.tag }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/webapp:${{ steps.image.outputs.tag }}


