name: Manual

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit to deploy
        required: false
        type: string
      environment:
        description: Target environment
        type: choice
        options:
          - staging
          - production
        default: staging
        required: true

jobs:
  build:
    uses: lneves75/gh-workflows/.github/workflows/ci.yaml@test-ci
    with:
      name: webapp
      build-args: '["COMMIT_HASH=abc"]'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

