name: Manual Build

on:
  workflow_dispatch:

jobs:
  trigger-deployment:
    uses: lneves75/gh-workflows/.github/workflows/build-image.yaml@build-args
    with:
      name: 'webapp'
      build-args: 'COMMIT_HASH=abc,TAG=alpine3.20-slim'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
